[package]
name = "glub_glub_bot"
version = "0.1.0"
authors = ["LonnonjamesD <xxl3m0nk1ngxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10.8", features = ["client", "gateway", "rustls_backend", "model", "framework"] }
tokio = { version = "1.8.1", features = ["macros", "rt-multi-thread"] }